### ISSUE TITLE
Please place all of the file in a single folder with the name `QuickLookup`

### ISSUE THREAD

**Issue by VKrishna04** [GTGalaxi/quick-lookup-ptrun#11]
**Describe the bug**
Please place all of the file in a single folder with the name `QuickLookup` such that we don't need to give permission for every single file and folder when installing and sinply give the path to extractor it will install it for us

**To Reproduce**
1. Go to Releases
2. Click on download X64 version package (did not check for AMD version)
3. extract all to `"C:\Program Files\PowerToys\RunPlugins\"
4. We have to give permission to ever single file that is being copied

**Expected behavior**
A single folder that is copied with one permission request.

**Environment (please complete the following information):**
 - OS: Win 11

**Comment by GTGalaxi** [comment]
Hey @VKrishna04,

Thanks for your feedback! If you download the release zip archive and right click it and click `Extract All...` it should automatically put the contents into a single folder that you can then copy to the plugins directory as seen below:

![image](https://github.com/user-attachments/assets/5b802737-58e0-4c0c-b0d5-e9c589fce1ee)

![image](https://github.com/user-attachments/assets/7ba5a7d0-0ce3-41b0-bfc8-72be1f50c9cc)

This can also be done with 7zip and any other archive tool like below:

![image](https://github.com/user-attachments/assets/24e1b581-b3ba-4431-94f1-a2af1b2c751e)

Thanks!
