### ISSUE TITLE
Installation Path

### ISSUE THREAD

**Issue by GTGalaxi** [GTGalaxi/quick-lookup-ptrun#2]
### Discussed in https://github.com/GTGalaxi/quick-lookup-ptrun/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **bdorr1105** April 16, 2023</sup>
I just wanted to point out that based on the per user PowerToys Installation, the path differs from the default Program Files path. The rest of the instructions are the same, however, the path is in a hidden directory.

C:\Users\<yourusername>\AppData\Local\PowerToys\modules\launcher\Plugins</div>

Update readme and installation instructions to reflect both installation types for PowerToys

**Comment by GTGalaxi** [comment]
Resolved in latest commit

**Comment by lounsberry** [comment]
Hi! I just wanted to let you know that I think the installation path changed again for installs in Program Files. The plugin folders appear to now need to be placed here:

C:\Program Files\PowerToys\RunPlugins

Just thought I'd let you know as I tried in the currently named directory, which required me to make the folders "modules\launcher\Plugins" and it did not work, which led me to deeper digging and found the answer by looking at another third party plugin instructions.

I appreciate your work on this! 😄

**Comment by GTGalaxi** [comment]
Thanks for the reminder, they changed the plugins directory and didn't make it move existing plugins over -.-
I will update the documentation later today!

**Comment by GTGalaxi** [comment]
@lounsberry This has been updated now in the readme and the release notes. Thanks again for the reminder!

**Comment by ifalatiksetlog** [comment]
@GTGalaxi The Local install directory moved to `C:\Users\<username>\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins`.
