### ISSUE TITLE
After PowerToys is upgraded to 0.75, quick-lookup cannot be loaded

### ISSUE THREAD

**Issue by Sec-Joe** [GTGalaxi/quick-lookup-ptrun#4]
![image](https://github.com/GTGalaxi/quick-lookup-ptrun/assets/31123200/2d6b44d3-3d77-47fe-898d-733d2688cc2b)

**Comment by tomlahr** [comment]
Same Procedure under PT 0.75.1...
![image](https://github.com/GTGalaxi/quick-lookup-ptrun/assets/99721319/aa2800ec-f0ad-4943-af21-2153703a76e5)

**Comment by GTGalaxi** [comment]
Thanks for raising this, I will look into it shortly

**Comment by htcfreek** [comment]
@GTGalaxi 
You simply have to add `public static string PluginID = "xxxxxxx"` to the `Main` method of your plugin. It is a new required starting with PT 0.75.0 .

**Comment by GTGalaxi** [comment]
Thanks for letting me know, do you have a link to somewhere where this new requirement is mentioned? I am overseas at the moment but will get it sorted asap.

**Comment by htcfreek** [comment]
> Thanks for letting me know, do you have a link to somewhere where this new requirement is mentioned? I am overseas at the moment but will get it sorted asap.

It is mentioned in the Readme/Release notes.

For an example you can look at: https://github.com/microsoft/PowerToys/pull/27468

**Comment by GTGalaxi** [comment]
Issue #4 resolved with latest release [1.3.1](https://github.com/GTGalaxi/quick-lookup-ptrun/releases/tag/v1.3.1), fulfilling new Plugin ID requirements for plugin validation added in Powertoys [0.75.0](https://github.com/microsoft/PowerToys/pull/27468).

Thanks @Sec-Joe, @tomlahr for bringing to my attention while I was overseas and @htcfreek for linking the documentation and commits related to the new changes.
