### ISSUE TITLE
QuickLookup no working at PowerToys 0.80.1

### ISSUE THREAD

**Issue by yuvalg72** [GTGalaxi/quick-lookup-ptrun#6]
Installed on
C:\Users\User\AppData\Local\PowerToys\RunPlugins\QuickLookup

Windows 11

Please help me :)

**Comment by GTGalaxi** [comment]
Hey @yuvalg72,

I believe that the path has changed yet again to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins` as Microsoft like to change things that don't need changing :'(

Please try this path instead and let me know if it works, I may need to update the install location in documentation and releases.

Thanks for trying it out :)
