### ISSUE TITLE
ql domain does not work with Censys

### ISSUE THREAD

**Issue by mike406** [GTGalaxi/quick-lookup-ptrun#7]
Censys shows the following for domain checks `Error 422. ip: value is not a valid IPv4 or IPv6 address. If you believe this is an error on our part, please [contact us](mailto:support@censys.io).`

**Comment by GTGalaxi** [comment]
Hey @mike406, thanks for raising this. 

Seems like Censys has changed how their query url is formatted. I will update it this afternoon and reply here when done.

**Comment by GTGalaxi** [comment]
Hey @mike406, this is fixed now sorry for the wait! I will be uploading the new release with the change later today
